name = "BatchedKernels"
uuid = "2fc592bb-64fa-475c-8993-177b89068dc6"
authors = ["Tim Hargreaves"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
